name: Report a Bug
description: File a Bug to be fixed ⚒️
title: "[Bug Reporting]: <title>"
labels:
  - Bug-Report
body:
  - type: input
    id: name
    attributes:
      label: empty
      description: emptr
      placeholder: empty
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Page URL
      description: Where did the Error occur?
      placeholder: https://example.com/home
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Error Type
      description: What type of Error Happened?
      options:
        - Wrong <title> Name
        - Wrong Favicon
        - No Game Page
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Explain
      description: Empty Field
      placeholder: If you chose Issue please describe the issue.
    validations:
      required: true
